[functions]
  # Esta es la nueva línea clave. Le dice al empaquetador que deje
  # esta librería intacta para que sus componentes nativos funcionen.
  external_node_modules = ["@libsql/client"]
  node_bundler = "esbuild"

# Este plugin sigue siendo necesario para instalar las dependencias
[[plugins]]
  package = "@netlify/plugin-functions-install-core"