# Configuración para que el empaquetador de funciones funcione correctamente
[functions]
  node_bundler = "esbuild"

# Plugin para instalar las dependencias de las funciones
# Esta es la parte que soluciona el error.
[[plugins]]
  package = "@netlify/plugin-functions-install-core"